### ISSUE TITLE
和支付宝推出的remax有什么区别吗？

### ISSUE THREAD

**Issue by zhangyanling77** [alipay/goldfish#22]

**Comment by yibuyisheng** [comment]
正如 [Remax 介绍](https://remaxjs.org/)所说：
> Remax 将 React 运行在小程序环境中，让你可以使用完整的 React 进行小程序开发。

Remax 的侧重点在于使用 React 体系开发小程序，并以此统一多端，所以重点在于解决视图层的问题。

Goldfish 侧重以 [Composition API](https://vue-composition-api-rfc.netlify.com/) 为体系开发小程序，基于[响应式](https://vuejs.org/v2/guide/reactivity.html)和函数化的状态管理方案，灵活、表达力强，且具备良好的测试友好性。当然，在不久的将来，Goldfish 也会对多端进行支持。

**Comment by zhangyanling77** [comment]
> 正如 [Remax 介绍](https://remaxjs.org/)所说：
> 
> > Remax 将 React 运行在小程序环境中，让你可以使用完整的 React 进行小程序开发。
> 
> Remax 的侧重点在于使用 React 体系开发小程序，并以此统一多端，所以重点在于解决视图层的问题。
> 
> Goldfish 侧重以 [Composition API](https://vue-composition-api-rfc.netlify.com/) 为体系开发小程序，基于[响应式](https://vuejs.org/v2/guide/reactivity.html)和函数化的状态管理方案，灵活、表达力强，且具备良好的测试友好性。当然，在不久的将来，Goldfish 也会对多端进行支持。

感谢回答
