### ISSUE TITLE
[Suggestion]Allow configure baseDir in mini.project.json

### ISSUE THREAD

**Issue by TNGD-YQ** [alipay/goldfish#49]
Currently the base directory of compileStream and copyStream are hard-coded. Although goldfish already provide process.env.BASE_DIR in the next release, but in my opinion I will like to have a single configuration entry, using official project config, instead of cross-env.
```js
const baseDir = path.resolve(
  cwd,
  process.env.BASE_DIR || require(`${cwd}${path.sep}mini.project.json`).baseDir || '.',
);
exports.baseDir = baseDir;
```

**Comment by yibuyisheng** [comment]
How about putting it in `mini.project.json` like this:
```json
{
  compilerOptions: {
    baseDir: 'xxx'
  }
}
```

**Comment by TNGD-YQ** [comment]
> How about putting it in `mini.project.json` like this:
> 
> ```js
> {
>   compilerOptions: {
>     baseDir: 'xxx'
>   }
> }
> ```

I don't mind the structure, but prefer to have only one config entry
